# Docker Environment Configuration
# Generated by docker:build command
# Copy this to .env and update with your values

APP_NAME="{{ $config->appName }}"
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=https://{{ $config->ssl?->domain ?? 'localhost' }}

LOG_CHANNEL=stack
LOG_LEVEL=error

@if($config->database)
# Database Configuration
DB_CONNECTION={{ $config->database->type === 'postgresql' ? 'pgsql' : ($config->database->type === 'mssql' ? 'sqlsrv' : $config->database->type) }}
@if($config->database->includeContainer)
DB_HOST={{ $config->database->type }}
@else
DB_HOST=your-remote-db-host
@endif
DB_PORT={{ $config->database->getDefaultPort() }}
DB_DATABASE=your_database
DB_USERNAME=your_username
DB_PASSWORD=your_password
@endif

@if($config->hasRedis())
# Redis Configuration
REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379

CACHE_DRIVER=redis
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
@else
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
@endif

# Mail Configuration
MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS="hello{{'@'}}{{ $config->ssl?->domain ?? 'example.com' }}"
MAIL_FROM_NAME="${APP_NAME}"

@if($config->hasDeploymentTarget('swarm'))
# Docker Swarm Configuration
DOCKER_REGISTRY=your-registry.com
IMAGE_TAG=latest
APP_DOMAIN={{ $config->ssl?->domain ?? 'localhost' }}
REPLICAS={{ $config->getDeploymentTarget('swarm')?->getReplicas() ?? 1 }}
@endif

@if($config->hasDeploymentTarget('kubernetes'))
# Kubernetes Configuration
DOCKER_REGISTRY=your-registry.com
IMAGE_TAG=latest
APP_DOMAIN={{ $config->ssl?->domain ?? 'localhost' }}
@endif
