#!/bin/bash
# Self-signed SSL Certificate Generator
# Generated by docker:build command

set -e

DOMAIN="{{ $domain }}"
SSL_DIR=".docker/ssl"
DAYS=365

echo "Generating self-signed SSL certificate for ${DOMAIN}..."

mkdir -p ${SSL_DIR}

# Generate private key
openssl genrsa -out ${SSL_DIR}/server.key 2048

# Generate certificate signing request
openssl req -new -key ${SSL_DIR}/server.key -out ${SSL_DIR}/server.csr -subj "/CN=${DOMAIN}/O=Development/C=US"

# Generate self-signed certificate
openssl x509 -req -days ${DAYS} -in ${SSL_DIR}/server.csr -signkey ${SSL_DIR}/server.key -out ${SSL_DIR}/server.crt

# Generate combined PEM file
cat ${SSL_DIR}/server.crt ${SSL_DIR}/server.key > ${SSL_DIR}/server.pem

# Cleanup CSR
rm ${SSL_DIR}/server.csr

echo "SSL certificate generated successfully!"
echo "Certificate: ${SSL_DIR}/server.crt"
echo "Private Key: ${SSL_DIR}/server.key"
echo ""
echo "Note: This is a self-signed certificate."
echo "Browsers will show a security warning."
