#!/bin/bash
# Let's Encrypt Certificate Initialization Script
# Generated by docker:build command

set -e

DOMAIN="{{ $domain }}"
EMAIL="{{ $email }}"
STAGING=0 # Set to 1 for testing

echo "Initializing Let's Encrypt for ${DOMAIN}..."

# Create required directories
mkdir -p certbot/conf certbot/www

# Check if certificates already exist
if [ -d "certbot/conf/live/${DOMAIN}" ]; then
    echo "Certificate already exists for ${DOMAIN}"
    echo "To renew, run: docker compose run --rm certbot renew"
    exit 0
fi

# Download recommended TLS parameters
if [ ! -f "certbot/conf/options-ssl-nginx.conf" ]; then
    curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf > certbot/conf/options-ssl-nginx.conf
fi

if [ ! -f "certbot/conf/ssl-dhparams.pem" ]; then
    curl -s https://raw.githubusercontent.com/certbot/certbot/master/certbot/certbot/ssl-dhparams.pem > certbot/conf/ssl-dhparams.pem
fi

# Create dummy certificate for nginx to start
echo "Creating dummy certificate..."
mkdir -p certbot/conf/live/${DOMAIN}
docker compose run --rm --entrypoint "\
    openssl req -x509 -nodes -newkey rsa:4096 -days 1 \
        -keyout '/etc/letsencrypt/live/${DOMAIN}/privkey.pem' \
        -out '/etc/letsencrypt/live/${DOMAIN}/fullchain.pem' \
        -subj '/CN=localhost'" certbot

# Start nginx
echo "Starting nginx..."
docker compose up -d nginx

# Delete dummy certificate
echo "Removing dummy certificate..."
docker compose run --rm --entrypoint "\
    rm -rf /etc/letsencrypt/live/${DOMAIN} && \
    rm -rf /etc/letsencrypt/archive/${DOMAIN} && \
    rm -rf /etc/letsencrypt/renewal/${DOMAIN}.conf" certbot

# Request real certificate
echo "Requesting Let's Encrypt certificate..."
STAGING_ARG=""
if [ $STAGING -eq 1 ]; then
    STAGING_ARG="--staging"
fi

docker compose run --rm --entrypoint "\
    certbot certonly --webroot -w /var/www/certbot \
        ${STAGING_ARG} \
        --email ${EMAIL} \
        -d ${DOMAIN} \
        --rsa-key-size 4096 \
        --agree-tos \
        --force-renewal" certbot

# Reload nginx
echo "Reloading nginx..."
docker compose exec nginx nginx -s reload

echo ""
echo "Let's Encrypt certificate installed successfully!"
echo "Certificate will auto-renew via the certbot container."
