; PHP Configuration for {{ $config->appName }}
; Generated by docker:build command

[PHP]
; Error handling
display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
log_errors = On
error_log = /var/log/php/error.log

; Memory and execution limits
memory_limit = 256M
max_execution_time = 120
max_input_time = 120
max_input_vars = 3000

; File uploads
upload_max_filesize = 64M
post_max_size = 64M

; Session
session.gc_maxlifetime = 7200
session.cookie_httponly = 1
session.cookie_secure = 1
session.cookie_samesite = "Lax"

; Date
date.timezone = UTC

; Opcache
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 0
opcache.save_comments = 1
opcache.fast_shutdown = 1

; Realpath cache
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; Security
expose_php = Off
allow_url_fopen = On
allow_url_include = Off

[MySQLi]
mysqli.default_socket = /var/run/mysqld/mysqld.sock

[Session]
session.save_handler = files
session.save_path = /var/lib/php/sessions

[Assertion]
zend.assertions = -1
